### ISSUE TITLE
elf.FilterSkeleton.grad.data.add_(sr * torch.sign(self.FilterSkeleton.data))

### ISSUE THREAD

**Issue by jucyLL** [fxmeng/Pruning-Filter-in-Filter#5]
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    train(epoch)
  File "main.py", line 83, in train
    model.update_skeleton(args.sr, args.threshold)
  File "/home/uze/projects/pytorchs/Pruning-Filter-in-Filter-master/models/resnet56.py", line 68, in update_skeleton
    out_mask = m.update_skeleton(sr, threshold)
  File "/home/uze/projects/pytorchs/Pruning-Filter-in-Filter-master/models/stripe.py", line 59, in update_skeleton
    self.FilterSkeleton.grad.data.add_(sr * torch.sign(self.FilterSkeleton.data))
AttributeError: 'NoneType' object has no attribute 'data'
请问这个问题应该怎么解决阿？

**Comment by fxmeng** [comment]
你改了代码吗？看着像没有先运行loss.backward()，梯度还没有呢

**Comment by jucyLL** [comment]
没有修改代码 运行python main.py --arch ResNet56 --data_path data --save checkpoint/ResNet56/baseline
 File "/home/uze/.local/share/Trash/files/Pruning-Filter-in-Filter-master.2/models/stripe.py", line 49, in _break
    self.FilterSkeleton = Parameter((self.FilterSkeleton.abs() > threshold), requires_grad=False)
TypeError: gt() received an invalid combination of arguments - got (NoneType), but expected one of:
 * (Tensor other)
      didn't match because some of the arguments have invalid types: (NoneType)
 * (Number other)
      didn't match because some of the arguments have invalid types: (NoneType)
也会出现这样错误 把prune的部分注释掉可以运行

**Comment by jucyLL** [comment]
确实是不小心修改了 感谢解答
